### ISSUE TITLE
No Unicode support? :-(

### ISSUE THREAD

**Issue by dertuxmalwieder** [rhaberkorn/sciteco#5] opened 2018-10-13 23:53 UTC
One would think that SciTECO could insert German umlauts just fine, but `iÄÖÜ$$` leads to visual garbage.

The manpage states:

> Currently however, SciTECO will only handle ASCII files.

That does not imply that direct input of non-ASCII characters into an empty document was forbidden, so I *thought* it could work...?

**Comment by rhaberkorn** [comment] 2018-10-16 16:39
Yes, that's true. SciTECO does currently not handle Unicode. Inserting Unicodes would be relatively easy to implement, but adding full Unicode support is unfortunately not trivial. The problem is that SciTECO as a language views documents as a sequence of characters/glyphs. `C` should move across an entire character, instead of a single byte in an Unicode glyph. With UTF8, documents are not "random accessible", though, so some clever heuristics need to be implemented. Also, I'm still somewhat unsure which rules to impose for interactions between buffers and Q-Registers - all of which could have different encodings. Not to mention that the parser needs to be Unicode-aware as well.

This feature however has long been on my `TODO` list, I have already begun implementing it (but then lost interest), and it will eventually be targetted.

Currently I'm working on a conversion of the entire codebase from C++ to plain C. (Haven't worked on that for some time...)

**Comment by dertuxmalwieder** [comment] 2018-10-23 14:51
I never assumed that this would be an easy task... :-) Unicode in plain C hurts a lot though, at least if you want to target the Microsoft compiler. Good luck, I guess. (But I'm seriously looking forward to it. In fact, it is the only real "blocker" for me. :-))

**Comment by dertuxmalwieder** [comment] 2021-10-04 13:24
I noticed that you're back from hibernation (well, conversion). Good! :-)
And thank you for the ongoing work.

**Comment by rhaberkorn** [comment] 2021-10-04 13:55
I want to do a release first before tackling Unicode. It's overdue. Somehow I got distracted again. Ah yes, I couldn't sort out all the problems with the Windows port because I did not have any Windows machine around and things evidently change and break every few years...

**Comment by dertuxmalwieder** [comment] 2021-10-13 01:09
I actually do (a 2019 one, running macOS 11). Considering that my own development projects don't get much love these days (my day only has 24 hours), is there anything I can do for you on it?

**Comment by rhaberkorn** [comment] 2021-10-14 12:48
Regarding Haiku: I've installed the new Haiku R1/beta3 release and cannot even clone my repository. It crashes the system. Last time, I did get it to build but it had strange crashes and Curses quirks that I could not debug and suspected to be OS bugs. It's simply not mature enough and probably not worth the effort to support. Although it would be nice to be one of the few available editors in their repos.

**Comment by rhaberkorn** [comment] 2024-08-22 16:37
I want to tackle Unicode once and for all this summer. I have the following ideas:

* The parser itself will stay purely ASCII, but source files can contain codepaged and UTF8 bytes. For him, it's just bytes. UTF32 TECO source files simply won't be supported and you could always convert it to UTF8 anyway. That's at least for the time being as an UTF8-aware parser could have advantages, for instance you could use umlauts in positions where single characters are expected, as in `^^ä`. The question is whether latin1 TECO source code makes any sense without the ability to actually edit TECO macros in latin1 or insert raw 128-255 bytes or whatever. So going all UTF8 for the parser might be the way to go. We will still support editing raw non-UTF8 binary files at the very least.
* In the UIs, we will always exclusively insert UTF8 into the command line macro. At least for the time being. Is it even worth considering code pages? I doubt it.
* Position integers will be glyph-addresses, not byte addresses. So commands will have to be UTF-aware if the underlying buffer is UTF.
* Every buffer will store the current position (`.`) and the end of the buffer (`Z`) in glyphs. The byte offsets are known from Scintilla. This gives us three tuples of known glyph-offset mappings. When navigating in UTF8 documents, being close to one of those anchor points will decide whether we are searching for the byte offsets from the left or right. Expressions like `.`, `Z`, `C`, `R` are guaranteed to be fast. Everything else has worst case linear complexity.
* Inserting UTF8 into raw buffers will simply insert the bytes (could be multiple bytes per glyph). There is no sensible conversion of course. The ASCII-subset of UTF8 will remain ASCII after insertion of course.
* Inserting UTF8 into codepaged buffers will for the time being just insert the raw bytes, ie. fail for everything outside of ASCII. In the future, we might try to automatically iconv to the target code page. This is not guaranteed to succeed, though.
* Inserting UTF8 into UTF16/32 buffers and from UTF16/32 registers can autoconvert the code points.
* Inserting raw byte registers into UTF buffers will just paste the bytes, so it might not result in valid Unicode.
* Inserting codepaged registers into UTF buffers will do the same, for the time being. See above, iconv could be used, but it's not a priority.
* There needs to be a new command for getting and setting the buffer's encoding: raw/ASCII, codepage, UTFx.
* The EOL normalization feature is left as it is. I want to keep constant conversions between glyph and byte offsets whereever possible, so it still makes sense to convert CRLF to LF in ASCII and UTF32 documents.
* I will try to keep support for non-widechar Curses libraries. If it turns out, we absolutely need the widechar libraries, I will not try to keep support for both. Non-widechar support will simply be dropped. Say goodbye to the DOS port!

**Comment by rhaberkorn** [comment] 2024-08-28 12:26
Regarding the curses variants, I found out:

* You need to link against widechar versions of ncurses (ncursesw) for Unicode handling. ncurses only differentiates between the two library names if the platform allow installing both. Ubuntu for instance has libncurses and libncursesw. On FreeBSD, libncurses is always the widechar version. But it ships both ncurses and ncursesw pkg-config files, both pointing to the same library. SciTECO therefore prefers ncursesw and falls back to ncurses.
* You don't necessarily have to use the widechar APIs even when linking against the widechar-variant of ncurses to display Unicode correctly. This is what I am now trying - avoiding widechar-variant specific APIs while still supporting Unicode. Scinterm appears to do the same - it does appear to use any of the widechar API. This definitely works on ncurses, but it remains to be seen what PDCurses and netbsd-curses does.
* Keeping non-widechar support is important only for certain minimalist systems, mostly embedded systems, where ncurses is actually built without widechar support. SciTECO does target those systems, although it's certainly not the smallest and leanest editor around.
* The thing with legacy systems (DOS, OS/2 etc.) - where there really is no curses with widechar support - is, that we don't support them anyway thanks to glib, which is a portability killer. (Many years ago, I did get OS/2 versions to build, but I think now that will be practically impossible.)

I can now at least input and display Unicode on all platforms, but I am not going to push it to master yet.

**Comment by rhaberkorn** [comment] 2024-08-28 19:22
Actually, I have command line editing and navigation in Unicode documents already working based on Scintilla's SCI_POSITIONRELATIVE and SCI_COUNTCHARACTERS. But it is way too slow. Apparently it really counts characters with every call. I hoped it would already be optimized by the SCI_ALLOCATELINECHARACTERINDEX. This is not the case.

SCI_POSITIONRELATIVE is also special in not being able to detect whether movements to the left are within the document's bounds as they reuse the 0 return value.

For instance in order to get the current glyph position (dot) using the character index, I will apparently have to:

    pos = SCI_GETCURRENTPOS()
    line = SCI_LINEFROMPOSITION(pos)
    glyphs = SCI_INDEXPOSITIONFROMLINE(line) + SCI_COUNTCHARACTERS(SCI_POSITIONFROMLINE(line), pos)

Which is a ridiculous 5 Scintilla messages instead of 1 for the single-byte case or 2 when using `SCI_COUNTCHARACTERS(0, SCI_GETCURRENTPOS())`.

**Comment by rhaberkorn** [comment] 2024-08-28 20:09
The inverse operation - getting the byte offset from a character/glyph index would be:

    line = SCI_LINEFROMINDEXPOSITION(pos)
    off = SCI_POSITIONRELATIVE(SCI_POSITIONFROMLINE(line), pos-SCI_INDEXPOSITIONFROMLINE(line))

Ie. 4 calls instead of the naive `SCI_POSITIONRELATIVE(0, pos)`.

Perhaps I will just do that for each and every conversion, along with an optimization for
left/right movements <= X with X being experimentally determined.
Eg. `12C` would still simply call `SCI_POSITIONRELATIVE(SCI_GETCURRENTPOS(), 12)`.
Consequently, `C` would be significantly faster than `.+1J` (2 vs. 9 messages).
In order to perform bounds checking, `12R` will have to consult the index first,
followed by one additional `SCI_POSITIONRELATIVE()` (6 messages).

That is not counting the `SCI_GETCODEPAGE()` message, necessary to determine whether we can actually consult the index.
Once we call that, it makes sense to optimize the single-byte encodings again.

You see, it's all very tricky to get done efficiently.

**Comment by rhaberkorn** [comment] 2024-08-29 02:09
I basically implemented the new glyph-based model and I am already dog feeding the Unicode version to myself.

I noticed another problem: Scintilla messages (`ES`) almost always work with byte offsets, no matter what's the buffer's encoding. In order to interface with them from macros - not all of them are mapped to proper SciTECO commands - there needs to be a wrapper around the glyph-to-byte conversion routines (although these algorithms could theoretically be rewritten in SciTECO, this would result in tons of redundancies). Sometimes, you can also work around the problem by using `ESGETCURRENTPOS$$` instead of `.`.

**Comment by rhaberkorn** [comment] 2024-08-29 12:06
Having an Unicode-aware parser becomes ever more likely. Otherwise syntax errors due to unknown characters become very cryptic, as it will be interpreted as a sequence of bytes causing syntax errors. Also, it would be nice if you could make use of the "international" keys on your keyboard and write `Mä` instead of `M[ä]`.

This leads me to another feature idea, that only really makes sense after introducing an Unicode-aware parser: When the parser encounters an unknown character, it could first consult a special Q-Register, eg. `^Xä` or `^XEä` (after typing `Eä`). If that register is defined, SciTECO could invoke it as a macro. That way, you could sort of extend the parser with unused glyphs. This would *not* destroy the parseability of SciTECO code, as the parser can simply skip over erroneous glyphs in parse-only mode. On the downside, this would effectively break some syntax error reporting in parse-only mode, so this should be a configurable feature.

**Comment by rhaberkorn** [comment] 2024-08-29 17:38
> I noticed another problem: Scintilla messages (`ES`) almost always work with byte offsets, no matter what's the buffer's encoding.

This also currently breaks fnkeys.tes in UTF-8 documents. Fixing it without easy access to the glyph-to-byte conversion would be quite tricky.

**Comment by rhaberkorn** [comment] 2024-08-30 19:00
Things left to do

* [ ] grosciteco doesn't draw Unicode boxes properly
* [ ] grosciteco does not format monospaced text (tables) correctly
* [ ] `^EUq` string building
* [ ] `Xq` inherit document's encoding
* [ ] `:Xq` convert to codepage of target register
* [ ] `Gq` convert to codepage of target document
* [ ] test the non-ASCII/UTF-8 codepages. They should render at least in Gtk.
* [ ] are `EE` and `^E` appropriate names for the new commands?
* [ ] codepage guessing: check for valid UTF-8, otherwise use a code page appropriate for the locale. Fallback to ASCII. Should be done as part of EOL normalization, so everything can be disabled together (pure 8-bit clean mode).
* [ ] Default codepage is always ASCII for new buffers and registers in pure 8-bit clean mode.

**Comment by rhaberkorn** [comment] 2024-08-30 22:39
We can't really guess a codepage based on the system locale, at least as long as it's based on UTF-8. g_get_charset() and friends will always return "UTF-8". Otherwise, we would have to parse several environment variables and other system API. And even that wouldn't be very helpful. For instance there are several Russian codepages around and we have no way of knowing which one should be preferred.

So the best thing we can do, if we would like to support codepage guessing: Either it's valid UTF-8, otherwise assume ANSI. Everything else has to be set explicitly using `EE`.

**Comment by rhaberkorn** [comment] 2024-08-31 13:23
`EE` is the escape surrogate flag in Standard TECO. This can be done with function key macros in SciTECO. `EE` (Edit Encoding) configures the document's encoding now and might also control iconv of documents.

`^E` was the form feed flag, which is also irrelevant for SciTECO as we don't read in pages. `^E` is now used to translate between glyph and byte addresses as often required when working with raw Scintilla messages (`ES`). It is heavily overloaded and can be used to validate addresses (glyph or byte) as well, so it might be used in all sorts of macros.

`^X` from Standard TECO which sort of looks like "transpose" is still reserved as a search flag (and if not, it would be better repurposed as a "cut" variant of `X`). `^T` might well be implemented in later versions of SciTECO as well. So `^E` as a sort of "encode address" command, reminding of its role for the document encoding, is probably not the worst choice. I am of course open for suggestions!

**Comment by rhaberkorn** [comment] 2024-09-02 13:46
> This leads me to another feature idea, that only really makes sense after introducing an Unicode-aware parser: When the parser encounters an unknown character, it could first consult a special Q-Register, eg. `^XÄ` (after typing `ä`) or `^XEÄ` (after typing `Eä`).

After thinking some more about it, it is not worth the trouble. If we would allow function key macros to work with all the printable characters, you could do exactly the same, without sacrificing syntax checking. For instance, if you had a macro `M§` for joining two lines, you could define `@^U[^F§]{M§} 1^_U[^F§]` which will do exactly the same. Redefining all printable characters would have many useful applications anyway: For instance, when working in Russian, you could map cyrillic characters to SciTECO commands according to your keyboard layout, so you don't have to switch between keyboard layouts all the time.

**Comment by rhaberkorn** [comment] 2024-09-02 22:06
The problem of translating between codepages could perhaps be more elegantly resolved by automatically iconving everything to UTF-8 on load and back to the source codepage during saves - similar on how the EOL style is normalized to LF in the buffers.
The conditionals (`"D`, `"A` etc) would work regardless of the buffer's encoding. Iconving between registers and buffers wouldn't be necessary. Also, editing documents in single-byte codepages would even work from the Curses version.

On the downside, navigation in these documents wouldn't benefit from the random-access that single-byte encodings allow. Furthermore, I don't see how you could change a wrong encoding after loading - the code page would have to be chosen at open-time as a parameter to EB. Guessing could also only work internally in EB.

**Comment by rhaberkorn** [comment] 2024-09-04 11:15
Just one more argument for a Unicode-aware parser: the `^V`, `^W` string building constructs cannot be supported with non-ANSI characters without it. We now have the information of a string argument's target encoding (defaulting to UTF-8). But we get fed single characters, which would make at least extremely cumbersome to perform Unicode case folding.

**Comment by rhaberkorn** [comment] 2024-09-04 21:54
> > This leads me to another feature idea, that only really makes sense after introducing an Unicode-aware parser: When the parser encounters an unknown character, it could first consult a special Q-Register, eg. `^XÄ` (after typing `ä`) or `^XEÄ` (after typing `Eä`).
> 
> After thinking some more about it, it is not worth the trouble. If we would allow function key macros to work with all the printable characters, you could do exactly the same, without sacrificing syntax checking. For instance, if you had a macro `M§` for joining two lines, you could define `@^U[^F§]{M§} 1^_U[^F§]` which will do exactly the same. Redefining all printable characters would have many useful applications anyway: For instance, when working in Russian, you could map cyrillic characters to SciTECO commands according to your keyboard layout, so you don't have to switch between keyboard layouts all the time.

On Gtk, where I have detailed information about the hardware keys pressed, I am now doing this automatically. He detects states where the SciTECO parser accepts only ANSI characters anyway and looks for ANSI keys in all of your keyboard layouts, effectively ignoring the keyboard layout whenever possible. This means that you don't usually have to manually switch keyboard layouts even when editing in a foreign non-latin-based language.

**Comment by rhaberkorn** [comment] 2024-09-09 17:36
I have pushed the first usable Unicode version. There are also a bunch of other new minor features and 8-bit cleanliness has been improved significantly. Non-ANSI single byte encodings are still only partially supported. You can use `EE` to configure a code page, it should be displayed correctly in Gtk, but you cannot actually insert non-latin text in these code pages. I have not decided which way to go - iconv'ing from UTF-8 to the target codepage whenever interacting with registers/buffers of different encodings; or iconv'ing during readin/readout (internally handling all non-ANSI codepages as Unicode). Both solutions somewhat suck.

The next thing I will do is making the SciTECO parser Unicode-aware, so you can use Unicode glyphs whereever the parser expects a single character. I will then probably rework the "function key macros" into more generic "key macros", so you can make more efficient use of your international non-latin keyboard keys.

**Comment by rhaberkorn** [comment] 2024-09-09 17:41
There have been a number of fixes in [sample.teco_ini](https://github.com/rhaberkorn/sciteco/commits/master/sample.teco_ini), you might want to merge into your `~/.teco_ini`.

**Comment by dertuxmalwieder** [comment] 2024-09-09 21:45
> The current state however is more than enough to edit some German text.

Which is more than enough *for me*. :-) 

Thank you a lot for your effort! I'll leave this open until you decide that **you're** happy with the feature...

**Comment by rhaberkorn** [comment] 2024-09-10 10:17
@dertuxmalwieder Have a try again at the Mac OS nightly builds. Since it's now preferring widechar builds of ncurses, I suspect that it could behave differently. Perhaps the visual glitches are now fixed:
https://github.com/rhaberkorn/sciteco/releases/download/nightly/sciteco-curses_nightly_macos_x86_64.pkg

**Comment by rhaberkorn** [comment] 2024-09-11 14:36
> I'll try the macOS nightlies tonight - sorry, been somewhat busy yesterday. I noticed a new problem on Windows with the Gtk3 UI though:
> 
That was a known limitation of the single-byte-based parser. Since it got fed single characters of an UTF-8 sequence, it could sometimes ask Gtk to draw these invalid sequences. The Curses UI had an analogous flickering instead.

With 6857807, this is also fixed. The entire language is Unicoded now. Feel free to `Xß` and `M⍝` to your heart's content.

[Nightly builds](https://github.com/rhaberkorn/sciteco/actions/runs/10813883872) should be ready with these latest changes.

**Comment by rhaberkorn** [comment] 2024-09-16 21:11
Now that we have Unicode support, I couldn't resist to implement icons in the Curses version. It requires [Nerd Fonts](https://www.nerdfonts.com/) and you need to add `0,512ED` to `~/.teco_ini`.
![screenshot-1726520831](https://github.com/user-attachments/assets/85314195-175b-495d-b7fc-45ef4b9782a5)

**Closed by rhaberkorn** 2024-09-16 21:11 UTC

**Comment by rhaberkorn** [comment] 2024-09-16 21:12
Support for other single-byte code pages is still left open, but this is only indirectly linked to Unicode.
